# Load the COG config first.
default_configs:
  configs/cog/cog_vwm.yaml

testing:
  problem:
    batch_size: 1
    tasks: [ SimpleCompareShape,
             # AndCompareShape,
      # ExistLastObjectSameObject,
      # ExistColorSpace, ExistShapeSpace, ExistColorSpace,
    ]
